
- name: Remove repo file
  file:
    state: absent
    path: /etc/yum.repos.d/open_three-tier-app.repo

- name: remove base tools and three tier app packages
  yum:
    state: absent 
    name: [u'httpie,haproxy']
    #name: "{{ item }}"
    #state: absent #only if items specified under name is present
  #with_items:
    #- httpie

